/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4383,
                                             1290,
                                             "Untitled",
                                             Dialog2Init_CB,
                                             Dialog2CloseButton_CB,
                                             Dialog2HelpButton_CB);
  LBL2_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             281,
                             538,
                    "Point Information:");

  PointInfoLabel = TecGUILabelAdd(Dialog2Manager,
                             500,
                             781,
                    "{ X Y Z } =");

  BTN1_BTN_D2 = TecGUIButtonAdd(Dialog2Manager,
                              734,
                              210,
                              2922,
                              144,
                    "Click and then select point",
                    StartProbe_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
