/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4383,
                                             2249,
                                             "Untitled",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  BTN1_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                              2096,
                              1022,
                              1479,
                              142,
                    "Push Button",
                    BTN1_BTN_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
