/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildTab1_1(LgIndex_t  Parent)
{
  if (Tab1_1Manager != BADDIALOGID)
    return;

  Tab1_1Manager = TecGUITabAddPage(Parent,
                               "Source data and options");
  TecGUIFrameAdd(Tab1_1Manager,
             78,
             793,
             4398,
             2173,
                    " Source variables ");

  TecGUIFrameAdd(Tab1_1Manager,
             101,
             85,
             4365,
             576,
                    " Options ");

  LBL3_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                               315,
                               926,
                    "Electron density:");

  RhoVarNum_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                         2126,
                                         883,
                                         2002,
                                         141,
                        RhoVarNum_OPT_T1_1_List,
                        RhoVarNum_OPT_T1_1_CB);

  HasGrad_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                   371,
                                   1105,
                                   3408,
                                   118,
                               "Gradient variables present",
                               HasGrad_TOG_T1_1_CB);

  LBL5_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                               315,
                               1299,
                    "Gradient X:");

  LBL7_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                               315,
                               1474,
                    "Gradient Y:");

  LBL9_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                               315,
                               1644,
                    "Gradient Z:");

  GradZVar_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                        2126,
                                        1611,
                                        2002,
                                        141,
                        GradZVar_OPT_T1_1_List,
                        GradZVar_OPT_T1_1_CB);

  GradYVar_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                        2126,
                                        1436,
                                        2002,
                                        141,
                        GradYVar_OPT_T1_1_List,
                        GradYVar_OPT_T1_1_CB);

  GradXVar_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                        2126,
                                        1261,
                                        2002,
                                        141,
                        GradXVar_OPT_T1_1_List,
                        GradXVar_OPT_T1_1_CB);

  HasHess_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                   371,
                                   1805,
                                   3296,
                                   118,
                               "Hessian variables present",
                               HasHess_TOG_T1_1_CB);

  LBL22_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                2003,
                    "Hessian XX:");

  HessXX_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                      2126,
                                      1956,
                                      2002,
                                      141,
                        HessXX_OPT_T1_1_List,
                        HessXX_OPT_T1_1_CB);

  LBL21_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                2168,
                    "Hessian XY:");

  LBL23_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                2338,
                    "Hessian XZ:");

  LBL24_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                2504,
                    "Hessian YY:");

  LBL25_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                2669,
                    "Hessian YZ:");

  LBL26_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                2839,
                    "Hessian ZZ:");

  HessZZ_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                      2126,
                                      2792,
                                      2002,
                                      141,
                        HessZZ_OPT_T1_1_List,
                        HessZZ_OPT_T1_1_CB);

  HessYZ_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                      2126,
                                      2627,
                                      2002,
                                      141,
                        HessYZ_OPT_T1_1_List,
                        HessYZ_OPT_T1_1_CB);

  HessYY_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                      2126,
                                      2461,
                                      2002,
                                      141,
                        HessYY_OPT_T1_1_List,
                        HessYY_OPT_T1_1_CB);

  HessXZ_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                      2126,
                                      2291,
                                      2002,
                                      141,
                        HessXZ_OPT_T1_1_List,
                        HessXZ_OPT_T1_1_CB);

  HessXY_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                      2126,
                                      2126,
                                      2002,
                                      141,
                        HessXY_OPT_T1_1_List,
                        HessXY_OPT_T1_1_CB);

  LBL27_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                315,
                                174,
                    "Calculate variables for:");

  PeriodicBC_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                      270,
                                      335,
                                      2520,
                                      118,
                               "Periodic boundary",
                               PeriodicBC_TOG_T1_1_CB);

  VolOrZone_RADIO_T1_1 = TecGUIRadioBoxAdd(Tab1_1Manager,
                                         2621,
                                         122,
                                         1901,
                                         297,
                                 "Selected zone",
                                 "All zones",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 VolOrZone_RADIO_T1_1_CB);

  SelZone_OPT_T1_1 = TecGUIOptionMenuAdd(Tab1_1Manager,
                                       236,
                                       472,
                                       4117,
                                       141,
                        SelZone_OPT_T1_1_List,
                        SelZone_OPT_T1_1_CB);

}

/**
 */
void BuildTab2_1(LgIndex_t  Parent)
{
  if (Tab2_1Manager != BADDIALOGID)
    return;

  Tab2_1Manager = TecGUITabAddPage(Parent,
                               "Variables to calculate");
  CalcGrad_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                    303,
                                    99,
                                    2283,
                                    118,
                               "Gradient vector",
                               CalcGrad_TOG_T2_1_CB);

  CalcMag_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                   303,
                                   245,
                                   2722,
                                   118,
                               "Gradient magnitude",
                               CalcMag_TOG_T2_1_CB);

  CalcHess_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                    303,
                                    396,
                                    1518,
                                    118,
                               "Hessian",
                               CalcHess_TOG_T2_1_CB);

  CalcGauss_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                     303,
                                     841,
                                     2700,
                                     118,
                               "Gaussian curvature",
                               CalcGauss_TOG_T2_1_CB);

  CalcEVdotGra_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                        303,
                                        992,
                                        4972,
                                        118,
                               "Dot product of gradient with eigenvectors",
                               CalcEVdotGra_TOG_T2_1_CB);

  CalcEb1_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                   303,
                                   1143,
                                   3127,
                                   118,
                               "Eberly '1-ridge' function",
                               CalcEb1_TOG_T2_1_CB);

  CalcEigRank_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                       303,
                                       1767,
                                       2767,
                                       118,
                               "Rank of eigenvalues",
                               CalcEigRank_TOG_T2_1_CB);

  CalcBTN_BTN_T2_1 = TecGUIButtonAdd(Tab2_1Manager,
                                   1305,
                                   2863,
                                   2160,
                                   141,
                    "Calculate variables",
                    CalcBTN_BTN_T2_1_CB);

  EB2Cutoff_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                     585,
                                     1611,
                                     3476,
                                     118,
                               "With density cutoff @ rho =",
                               EB2Cutoff_TOG_T2_1_CB);

  EB2CutoffVal_TF_T2_1 = TecGUITextFieldAdd(Tab2_1Manager,
                                          3082,
                                          1592,
                                          1237,
                                          141,
                       EB2CutoffVal_TF_T2_1_CB);

  EB1Cutoff_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                     585,
                                     1299,
                                     3476,
                                     118,
                               "With density cutoff @ rho =",
                               EB1Cutoff_TOG_T2_1_CB);

  EB1CutoffVal_TF_T2_1 = TecGUITextFieldAdd(Tab2_1Manager,
                                          3082,
                                          1271,
                                          1237,
                                          141,
                       EB1CutoffVal_TF_T2_1_CB);

  LBL14_LBL_T2_1 = TecGUILabelAdd(Tab2_1Manager,
                                4398,
                                1597,
                    "e");

  LBL13_LBL_T2_1 = TecGUILabelAdd(Tab2_1Manager,
                                4398,
                                1271,
                    "e");

  CalcES_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                  303,
                                  543,
                                  2081,
                                  118,
                               "Eigen system",
                               CalcES_TOG_T2_1_CB);

  CalcLap_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                   303,
                                   694,
                                   1676,
                                   118,
                               "Laplacian",
                               CalcLap_TOG_T2_1_CB);

  CalcEb2_TOG_T2_1 = TecGUIToggleAdd(Tab2_1Manager,
                                   303,
                                   1455,
                                   3127,
                                   118,
                               "Eberly '2-ridge' function",
                               CalcEb2_TOG_T2_1_CB);

}

/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4805,
                                             3236,
                                             "Calculate variables",
                                             Dialog2Init_CB,
                                             Dialog2CloseButton_CB,
                                             Dialog2HelpButton_CB);
  TAB1_TB_D2 = TecGUITabAdd(Dialog2Manager,
                          22,
                          179,
                          4770,
                          3052,
                    TAB1_TBA_D2_CB,
                    TAB1_TBD_D2_CB);

  BuildTab1_1(TAB1_TB_D2);
  BuildTab2_1(TAB1_TB_D2);
}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
