/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Tab1_1Manager = BADDIALOGID;
LgIndex_t LBL3_LBL_T1_1 = BADDIALOGID;
LgIndex_t RhoVarNum_OPT_T1_1 = BADDIALOGID;
LgIndex_t HasGrad_TOG_T1_1 = BADDIALOGID;
LgIndex_t LBL5_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBL7_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBL9_LBL_T1_1 = BADDIALOGID;
LgIndex_t GradZVar_OPT_T1_1 = BADDIALOGID;
LgIndex_t GradYVar_OPT_T1_1 = BADDIALOGID;
LgIndex_t GradXVar_OPT_T1_1 = BADDIALOGID;
LgIndex_t HasHess_TOG_T1_1 = BADDIALOGID;
LgIndex_t LBL22_LBL_T1_1 = BADDIALOGID;
LgIndex_t HessXX_OPT_T1_1 = BADDIALOGID;
LgIndex_t LBL21_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBL23_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBL24_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBL25_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBL26_LBL_T1_1 = BADDIALOGID;
LgIndex_t HessZZ_OPT_T1_1 = BADDIALOGID;
LgIndex_t HessYZ_OPT_T1_1 = BADDIALOGID;
LgIndex_t HessYY_OPT_T1_1 = BADDIALOGID;
LgIndex_t HessXZ_OPT_T1_1 = BADDIALOGID;
LgIndex_t HessXY_OPT_T1_1 = BADDIALOGID;
LgIndex_t LBL27_LBL_T1_1 = BADDIALOGID;
LgIndex_t PeriodicBC_TOG_T1_1 = BADDIALOGID;
LgIndex_t VolOrZone_RADIO_T1_1 = BADDIALOGID;
LgIndex_t SelZone_OPT_T1_1 = BADDIALOGID;
LgIndex_t Tab2_1Manager = BADDIALOGID;
LgIndex_t CalcGrad_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcMag_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcHess_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcGauss_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcEVdotGra_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcEb1_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcEigRank_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcBTN_BTN_T2_1 = BADDIALOGID;
LgIndex_t EB2Cutoff_TOG_T2_1 = BADDIALOGID;
LgIndex_t EB2CutoffVal_TF_T2_1 = BADDIALOGID;
LgIndex_t EB1Cutoff_TOG_T2_1 = BADDIALOGID;
LgIndex_t EB1CutoffVal_TF_T2_1 = BADDIALOGID;
LgIndex_t LBL14_LBL_T2_1 = BADDIALOGID;
LgIndex_t LBL13_LBL_T2_1 = BADDIALOGID;
LgIndex_t CalcES_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcLap_TOG_T2_1 = BADDIALOGID;
LgIndex_t CalcEb2_TOG_T2_1 = BADDIALOGID;
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t TAB1_TB_D2 = BADDIALOGID;
