/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Sidebar1Manager;
extern void BuildSidebar1(void);
extern LgIndex_t  SLSelSphere_SLST_S1;
extern LgIndex_t  TGLSphereVis_TOG_S1;
extern LgIndex_t  MLSelGB_MLST_S1;
extern LgIndex_t  BTNTogMode_BTN_S1;
extern LgIndex_t  BTNExitRes_BTN_S1;
extern LgIndex_t  BTNSphereDel_BTN_S1;
extern LgIndex_t  BTNAllGB_BTN_S1;
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  MLSelCPs_MLST_D1;
extern LgIndex_t  TGLInt_TOG_D1;
extern LgIndex_t  MLSelVars_MLST_D1;
extern LgIndex_t  TGLOpenSys_TOG_D1;
extern LgIndex_t  LBLCutoff_LBL_D1;
extern LgIndex_t  TFCutoff_TF_D1;
extern LgIndex_t  LBLRad_LBL_D1;
extern LgIndex_t  TFRad_TF_D1;
extern LgIndex_t  LBLLevel_LBL_D1;
extern LgIndex_t  TFLevel_TFS_D1;
extern LgIndex_t  LBLNumTri_LBL_D1;
extern LgIndex_t  LBLIB2_LBL_D1;
extern LgIndex_t  LBLIBDist_LBL_D1;
extern LgIndex_t  LBLIBAng_LBL_D1;
extern LgIndex_t  TFIBDist_TF_D1;
extern LgIndex_t  TFIBAng_TF_D1;
extern LgIndex_t  LBLIBDeg_LBL_D1;
extern LgIndex_t  BTNRun_BTN_D1;
extern LgIndex_t  LBL19_LBL_D1;
extern LgIndex_t  TFSTPts_TF_D1;
extern LgIndex_t  RBRadMode_RADIO_D1;
