/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildTab1_1(LgIndex_t  Parent)
{
  if (Tab1_1Manager != BADDIALOGID)
    return;

  Tab1_1Manager = TecGUITabAddPage(Parent,
                               "Setup");
  TecGUIFrameAdd(Tab1_1Manager,
             184,
             1530,
             10169,
             1075,
                    "Gradient bundle parameters");

  TecGUIFrameAdd(Tab1_1Manager,
             2651,
             77,
             7748,
             1384,
                    " Integration Variables ");

  TecGUIFrameAdd(Tab1_1Manager,
             138,
             77,
             2375,
             1375,
                    " Select CP(s) ");

  BTNRun_BTN_T1_1 = TecGUIButtonAdd(Tab1_1Manager,
                                  8924,
                                  2653,
                                  1014,
                                  232,
                    "       Run\n",
                    BTNRun_BTN_T1_1_CB);

  TFSTPts_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     9477,
                                     1578,
                                     760,
                                     145,
                       TFSTPts_TF_T1_1_CB);

  LBLSTPts_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   7286,
                                   1598,
                    "# Gradient path points:");

  LBLNumTri_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                    7217,
                                    1782,
                    "--> Num Triangles");

  TFSdRad_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     2144,
                                     1927,
                                     714,
                                     145,
                       TFSdRad_TF_T1_1_CB);

  LBLRad_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                 345,
                                 1791,
                    "Radial sphere approx:");

  RBRadMode_RADIO_T1_1 = TecGUIRadioBoxAdd(Tab1_1Manager,
                                         345,
                                         2256,
                                         2882,
                                         300,
                                 "Absolute",
                                 "Fraction of min CP dist.",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 RBRadMode_RADIO_T1_1_CB);

  TFCutoff_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                      5764,
                                      1578,
                                      1291,
                                      145,
                       TFCutoff_TF_T1_1_CB);

  LBLCutoff_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                    3735,
                                    1598,
                    "System Rho Cutoff:");

  MLSelVars_MLST_T1_1 = TecGUIListAdd(Tab1_1Manager,
                                    2697,
                                    406,
                                    7425,
                                    1055,
                       1,
                       MLSelVars_MLST_T1_1_CB);

  SCPrecise_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                   4012,
                                   232,
                                   1199,
                                   106,
                    0,
                    100,
                    0,
                    SCPrecise_SC_T1_1_CB,
                    SCPrecise_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCPrecise_SC_T1_1,FALSE);

  LBLPreci1_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                    2813,
                                    232,
                    "Precision:");

  MLSelCPs_MLST_T1_1 = TecGUIListAdd(Tab1_1Manager,
                                   230,
                                   145,
                                   2167,
                                   1326,
                       1,
                       MLSelCPs_MLST_T1_1_CB);

  LBLPrecise_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                     5811,
                                     222,
                    "Label");

  TGLsGP_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                  4911,
                                  2750,
                                  1683,
                                  116,
                               "Save GPs",
                               TGLsGP_TOG_T1_1_CB);

  TGLsGB_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                  6410,
                                  2750,
                                  1706,
                                  116,
                               "Save GBs",
                               TGLsGB_TOG_T1_1_CB);

  LBLLevel_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   3182,
                                   1782,
                    "Minimum number of gradient bundles (GB)");

  LBLBPGBa_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   3182,
                                   2285,
                    "Number of bond path coincident GBs:");

  LBLGBMaxSD_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                     3182,
                                     2450,
                    "Maximum GB surface gradient path spacing:");

  LBLSDtightle_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                       3182,
                                       2121,
                    "Subdivision tightness around bond/ring features");

  TGLNoSphInt_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                       392,
                                       1607,
                                       2951,
                                       116,
                               "Radial sphere approx.",
                               TGLNoSphInt_TOG_T1_1_CB);

  SCSDtight_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                   9016,
                                   2101,
                                   1199,
                                   106,
                    0,
                    100,
                    0,
                    SCSDtight_SC_T1_1_CB,
                    SCSDtight_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCSDtight_SC_T1_1,FALSE);

  SCBPGBs_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                 9016,
                                 2275,
                                 1199,
                                 106,
                    0,
                    100,
                    0,
                    SCBPGBs_SC_T1_1_CB,
                    SCBPGBs_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCBPGBs_SC_T1_1,FALSE);

  SCEGPDist_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                   9016,
                                   2450,
                                   1199,
                                   106,
                    0,
                    100,
                    0,
                    SCEGPDist_SC_T1_1_CB,
                    SCEGPDist_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCEGPDist_SC_T1_1,FALSE);

  LBLSDtight_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                     8324,
                                     2111,
                    "Label");

  LBLBPGBs_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   8324,
                                   2275,
                    "Label");

  LBLEGPDistTy_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                       8324,
                                       2450,
                    "Label");

  LBLBPGBi_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   3182,
                                   1956,
                    "Maximum GB subdivision level (around bond/ring features):");

  LBLBPGBInit_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                      8324,
                                      1937,
                    "Label");

  SCMinGBs_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                  9016,
                                  1762,
                                  1199,
                                  106,
                    0,
                    100,
                    0,
                    SCMinGBs_SC_T1_1_CB,
                    SCMinGBs_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCMinGBs_SC_T1_1,FALSE);

  SCBPGBInit_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                    9016,
                                    1937,
                                    1199,
                                    106,
                    0,
                    100,
                    0,
                    SCBPGBInit_SC_T1_1_CB,
                    SCBPGBInit_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCBPGBInit_SC_T1_1,FALSE);

  TGLSphTest_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                      161,
                                      2905,
                                      622,
                                      116,
                               ".",
                               TGLSphTest_TOG_T1_1_CB);

  TGL_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                               7010,
                               184,
                               3989,
                               116,
                               "Enter atomic reference energies",
                               TGL_TOG_T1_1_CB);

  LBL34_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                345,
                                1946,
                    "GP seed radius:");

  TFRad_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                   2144,
                                   1762,
                                   714,
                                   145,
                       TFRad_TF_T1_1_CB);

  LBL36_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                345,
                                2101,
                    "H atom seed radius:");

  TFHSdR_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                    2144,
                                    2091,
                                    714,
                                    145,
                       TFHSdR_TF_T1_1_CB);

}

/**
 */
void BuildTab3_1(LgIndex_t  Parent)
{
  if (Tab3_1Manager != BADDIALOGID)
    return;

  Tab3_1Manager = TecGUITabAddPage(Parent,
                               "Results");
  TecGUIFrameAdd(Tab3_1Manager,
             46,
             77,
             3758,
             1346,
                    " CP Sphere ");

  TecGUIFrameAdd(Tab3_1Manager,
             46,
             1510,
             3758,
             1501,
                    "Properties");

  TecGUIFrameAdd(Tab3_1Manager,
             3874,
             77,
             6525,
             2198,
                    "Gradient Bundles");

  TecGUIFrameAdd(Tab3_1Manager,
             7402,
             1326,
             2628,
             929,
                    "User-defined GB");

  TecGUIFrameAdd(Tab3_1Manager,
             3897,
             2372,
             6479,
             619,
                    "Sphere contours");

  SLSelSphere_SLST_T3_1 = TecGUIListAdd(Tab3_1Manager,
                                      1752,
                                      154,
                                      2006,
                                      871,
                       0,
                       SLSelSphere_SLST_T3_1_CB);

  TGLSphereVis_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                        345,
                                        271,
                                        1383,
                                        116,
                               "Visible",
                               TGLSphereVis_TOG_T3_1_CB);

  BTNSphereDel_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                        368,
                                        639,
                                        853,
                                        145,
                    "Delete",
                    BTNSphereDel_BTN_T3_1_CB);

  SLSelVar_SLST_T3_1 = TecGUIListAdd(Tab3_1Manager,
                                   322,
                                   1607,
                                   3297,
                                   871,
                       0,
                       SLSelVar_SLST_T3_1_CB);

  MLSelGB_MLST_T3_1 = TecGUIListAdd(Tab3_1Manager,
                                  3943,
                                  164,
                                  3205,
                                  2053,
                       1,
                       MLSelGB_MLST_T3_1_CB);

  BTNAllGB_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                    8877,
                                    978,
                                    1337,
                                    145,
                    "Activate all",
                    BTNAllGB_BTN_T3_1_CB);

  BTNTogMode_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                      7263,
                                      978,
                                      1545,
                                      145,
                    "Toggle mode",
                    BTNTogMode_BTN_T3_1_CB);

  TFNumContours_TF_T3_1 = TecGUITextFieldAdd(Tab3_1Manager,
                                           5188,
                                           2469,
                                           1245,
                                           145,
                       TFNumContours_TF_T3_1_CB);

  LBL9_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                               6641,
                               2479,
                    "Number of contours");

  RBLogLin_RADIO_T3_1 = TecGUIRadioBoxAdd(Tab3_1Manager,
                                        8947,
                                        2401,
                                        1037,
                                        300,
                                 "log",
                                 "linear",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 RBLogLin_RADIO_T3_1_CB);

  RBCntSrc_RADIO_T3_1 = TecGUIRadioBoxAdd(Tab3_1Manager,
                                        7678,
                                        2673,
                                        1314,
                                        300,
                                 "selected",
                                 "all",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 RBCntSrc_RADIO_T3_1_CB);

  LBLCntSrc_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                    5188,
                                    2740,
                    "Make contour values from");

  LBL13_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                8831,
                                2740,
                    "sphere(s)");

  TGLShowMesh_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                       345,
                                       435,
                                       1890,
                                       116,
                               "Show Mesh",
                               TGLShowMesh_TOG_T3_1_CB);

  BTNSelGB_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                    8001,
                                    2082,
                                    1222,
                                    145,
                    "Select GB",
                    BTNSelGB_BTN_T3_1_CB);

  TFGrpNum_TF_T3_1 = TecGUITextFieldAdd(Tab3_1Manager,
                                      8924,
                                      1898,
                                      714,
                                      145,
                       TFGrpNum_TF_T3_1_CB);

  LBL20_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                7586,
                                1937,
                    "Group #");

  LBL21_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                7632,
                                1423,
                    "1. Activate boundary with\n    toggle mode\n2. Select GB element \n     within boundary");

  BTNFndBas_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                     7540,
                                     145,
                                     2352,
                                     232,
                    "Find special gradient\nbundles",
                    BTNFndBas_BTN_T3_1_CB);

  BTNSmooth_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                     622,
                                     2837,
                                     2813,
                                     145,
                    "Smooth selected variable",
                    BTNSmooth_BTN_T3_1_CB);

  TGLSmoothAll_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                        276,
                                        2702,
                                        2490,
                                        116,
                               "Smooth all atoms",
                               TGLSmoothAll_TOG_T3_1_CB);

  SCRad_SC_T3_1 = TecGUIScaleAdd(Tab3_1Manager,
                               415,
                               1259,
                               2605,
                               106,
                    0,
                    100,
                    0,
                    SCRad_SC_T3_1_CB,
                    SCRad_SCD_T3_1_CB);


  TecGUIScaleShowNumericDisplay(SCRad_SC_T3_1,FALSE);

  TGLRadAll_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                     438,
                                     1084,
                                     1867,
                                     116,
                               "All Spheres",
                               TGLRadAll_TOG_T3_1_CB);

  TGLRadAbs_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                     1867,
                                     1084,
                                     1614,
                                     116,
                               "Absolute",
                               TGLRadAbs_TOG_T3_1_CB);

  LBL27_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                438,
                                823,
                    "Radius:");

  LBLRadLab_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                    3113,
                                    1249,
                    "Label");

  TGL_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                               7402,
                               745,
                               576,
                               116,
                               ".",
                               TGL_TOG_T3_1_CB);

  LBL31_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                7932,
                                687,
                    "Save special gradient\nbundle surfaces");

  TGLINSV_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                   276,
                                   2527,
                                   4773,
                                   116,
                               "Only show normalized, scaled variables",
                               TGLINSV_TOG_T3_1_CB);

  TFGBSub_TF_T3_1 = TecGUITextFieldAdd(Tab3_1Manager,
                                     9200,
                                     464,
                                     530,
                                     145,
                       TFGBSub_TF_T3_1_CB);

  LBL32_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                7356,
                                493,
                    "Boundary refinement");

}

/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             10550,
                                             3262,
                                             "Gradient Bundle Analysis",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             NULL)
;  TAB1_TB_D1 = TecGUITabAdd(Dialog1Manager,
                          46,
                          184,
                          10469,
                          3050,
                    TAB1_TBA_D1_CB,
                    TAB1_TBD_D1_CB);

  BuildTab1_1(TAB1_TB_D1);
  BuildTab3_1(TAB1_TB_D1);
}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
