/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildTab1_1(LgIndex_t  Parent)
{
  if (Tab1_1Manager != BADDIALOGID)
    return;

  Tab1_1Manager = TecGUITabAddPage(Parent,
                               "Setup");
  TecGUIFrameAdd(Tab1_1Manager,
             189,
             1661,
             9971,
             938,
                    " Sphere Mesh Parameters ");

  TecGUIFrameAdd(Tab1_1Manager,
             189,
             1297,
             9998,
             267,
                    " System Boundary Parameters ");

  TecGUIFrameAdd(Tab1_1Manager,
             2587,
             79,
             7600,
             1138,
                    " Integration Variables ");

  TecGUIFrameAdd(Tab1_1Manager,
             135,
             79,
             2330,
             1138,
                    " Select CP(s) ");

  BTNRun_BTN_T1_1 = TecGUIButtonAdd(Tab1_1Manager,
                                  8738,
                                  2651,
                                  1029,
                                  233,
                    "       Run\n",
                    BTNRun_BTN_T1_1_CB);

  TFSTPts_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                     9348,
                                     1371,
                                     772,
                                     142,
                       TFSTPts_TF_T1_1_CB);

  LBLSTPts_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   7153,
                                   1416,
                    "# Gradient path points:");

  LBLNumTri_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                    7031,
                                    1769,
                    "--> Num Triangles");

  TFRad_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                   1273,
                                   1832,
                                   718,
                                   142,
                       TFRad_TF_T1_1_CB);

  LBLRad_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                 379,
                                 1855,
                    "Radius:");

  RBRadMode_RADIO_T1_1 = TecGUIRadioBoxAdd(Tab1_1Manager,
                                         406,
                                         2054,
                                         2872,
                                         295,
                                 "Absolute",
                                 "Fraction of min CP dist.",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 RBRadMode_RADIO_T1_1_CB);

  TFCutoff_TF_T1_1 = TecGUITextFieldAdd(Tab1_1Manager,
                                      5731,
                                      1365,
                                      1300,
                                      142,
                       TFCutoff_TF_T1_1_CB);

  LBLCutoff_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                    3658,
                                    1411,
                    "System Rho Cutoff:");

  MLSelVars_MLST_T1_1 = TecGUIListAdd(Tab1_1Manager,
                                    2669,
                                    324,
                                    7438,
                                    870,
                       1,
                       MLSelVars_MLST_T1_1_CB);

  SCPrecise_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                   5175,
                                   176,
                                   1192,
                                   108,
                    0,
                    100,
                    0,
                    SCPrecise_SC_T1_1_CB,
                    SCPrecise_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCPrecise_SC_T1_1,FALSE);

  LBLPreci1_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                    4010,
                                    170,
                    "Precision:");

  MLSelCPs_MLST_T1_1 = TecGUIListAdd(Tab1_1Manager,
                                   216,
                                   142,
                                   2154,
                                   1052,
                       1,
                       MLSelCPs_MLST_T1_1_CB);

  LBLPrecise_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                     6950,
                                     176,
                    "Label");

  TGLsGP_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                  406,
                                  1382,
                                  1680,
                                  119,
                               "Save GPs",
                               TGLsGP_TOG_T1_1_CB);

  TGLsGB_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                  2072,
                                  1382,
                                  1693,
                                  119,
                               "Save GBs",
                               TGLsGB_TOG_T1_1_CB);

  LBLLevel_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   2736,
                                   1769,
                    "Minimum number of gradient bundles (GB)");

  LBLBPGBa_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   2736,
                                   2270,
                    "Number of bond path coincident GBs:");

  LBLGBMaxSD_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                     2736,
                                     2435,
                    "Maximum GB surface gradient path spacing:");

  LBLSDtightle_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                       2736,
                                       2105,
                    "Subdivision tightness around bond/ring features");

  TGLNoSphInt_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                       7939,
                                       159,
                                       2940,
                                       119,
                               "Radial sphere approx.",
                               TGLNoSphInt_TOG_T1_1_CB);

  SCSDtight_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                   8820,
                                   2088,
                                   1192,
                                   108,
                    0,
                    100,
                    0,
                    SCSDtight_SC_T1_1_CB,
                    SCSDtight_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCSDtight_SC_T1_1,FALSE);

  SCBPGBs_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                 8820,
                                 2264,
                                 1192,
                                 108,
                    0,
                    100,
                    0,
                    SCBPGBs_SC_T1_1_CB,
                    SCBPGBs_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCBPGBs_SC_T1_1,FALSE);

  SCEGPDist_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                   8820,
                                   2435,
                                   1192,
                                   108,
                    0,
                    100,
                    0,
                    SCEGPDist_SC_T1_1_CB,
                    SCEGPDist_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCEGPDist_SC_T1_1,FALSE);

  LBLSDtight_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                     8169,
                                     2094,
                    "Label");

  LBLBPGBs_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   8169,
                                   2264,
                    "Label");

  LBLEGPDistTy_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                       8169,
                                       2435,
                    "Label");

  LBLBPGBi_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                   2736,
                                   1934,
                    "Maximum GB subdivision level (around bond/ring features):");

  LBLBPGBInit_LBL_T1_1 = TecGUILabelAdd(Tab1_1Manager,
                                      8169,
                                      1923,
                    "Label");

  SCMinGBs_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                  8820,
                                  1746,
                                  1192,
                                  108,
                    0,
                    100,
                    0,
                    SCMinGBs_SC_T1_1_CB,
                    SCMinGBs_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCMinGBs_SC_T1_1,FALSE);

  SCBPGBInit_SC_T1_1 = TecGUIScaleAdd(Tab1_1Manager,
                                    8820,
                                    1917,
                                    1192,
                                    108,
                    0,
                    100,
                    0,
                    SCBPGBInit_SC_T1_1_CB,
                    SCBPGBInit_SCD_T1_1_CB);


  TecGUIScaleShowNumericDisplay(SCBPGBInit_SC_T1_1,FALSE);

  TGLSphTest_TOG_T1_1 = TecGUIToggleAdd(Tab1_1Manager,
                                      392,
                                      2407,
                                      623,
                                      119,
                               ".",
                               TGLSphTest_TOG_T1_1_CB);

}

/**
 */
void BuildTab3_1(LgIndex_t  Parent)
{
  if (Tab3_1Manager != BADDIALOGID)
    return;

  Tab3_1Manager = TecGUITabAddPage(Parent,
                               "Results");
  TecGUIFrameAdd(Tab3_1Manager,
             338,
             216,
             3143,
             1212,
                    " CP Sphere ");

  TecGUIFrameAdd(Tab3_1Manager,
             392,
             1490,
             3102,
             1166,
                    "Properties");

  TecGUIFrameAdd(Tab3_1Manager,
             3631,
             204,
             6381,
             1781,
                    "Gradient Bundles");

  TecGUIFrameAdd(Tab3_1Manager,
             7126,
             2065,
             2885,
             580,
                    " Export ");

  TecGUIFrameAdd(Tab3_1Manager,
             3644,
             2071,
             3346,
             580,
                    " GB Region ");

  SLSelSphere_SLST_T3_1 = TecGUIListAdd(Tab3_1Manager,
                                      1761,
                                      250,
                                      1652,
                                      779,
                       0,
                       SLSelSphere_SLST_T3_1_CB);

  TGLSphereVis_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                        392,
                                        364,
                                        1381,
                                        119,
                               "Visible",
                               TGLSphereVis_TOG_T3_1_CB);

  BTNSphereDel_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                        420,
                                        739,
                                        853,
                                        142,
                    "Delete",
                    BTNSphereDel_BTN_T3_1_CB);

  SLSelVar_SLST_T3_1 = TecGUIListAdd(Tab3_1Manager,
                                   460,
                                   1587,
                                   2872,
                                   870,
                       0,
                       SLSelVar_SLST_T3_1_CB);

  MLSelGB_MLST_T3_1 = TecGUIListAdd(Tab3_1Manager,
                                  3698,
                                  301,
                                  3441,
                                  1599,
                       1,
                       MLSelGB_MLST_T3_1_CB);

  BTNAllGB_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                    7316,
                                    796,
                                    1883,
                                    142,
                    "         Activate All",
                    BTNAllGB_BTN_T3_1_CB);

  BTNTogMode_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                      7316,
                                      597,
                                      1883,
                                      142,
                    "      Toggle Mode",
                    BTNTogMode_BTN_T3_1_CB);

  TFNumContours_TF_T3_1 = TecGUITextFieldAdd(Tab3_1Manager,
                                           338,
                                           2748,
                                           1246,
                                           142,
                       TFNumContours_TF_T3_1_CB);

  LBL9_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                               1747,
                               2771,
                    "Number of contours");

  RBLogLin_RADIO_T3_1 = TecGUIRadioBoxAdd(Tab3_1Manager,
                                        4010,
                                        2697,
                                        1029,
                                        295,
                                 "log",
                                 "linear",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 RBLogLin_RADIO_T3_1_CB);

  RBCntSrc_RADIO_T3_1 = TecGUIRadioBoxAdd(Tab3_1Manager,
                                        7695,
                                        2702,
                                        1327,
                                        295,
                                 "selected",
                                 "all",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 RBCntSrc_RADIO_T3_1_CB);

  LBLCntSrc_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                    5256,
                                    2765,
                    "Make contour values from");

  LBL13_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                8833,
                                2765,
                    "sphere(s)");

  BTNExport_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                     7424,
                                     2446,
                                     1652,
                                     142,
                    "Export to CSV",
                    BTNExport_BTN_T3_1_CB);

  TGLExGBs_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                    7302,
                                    2150,
                                    3468,
                                    119,
                               "Include ALL individual GBs",
                               TGLExGBs_TOG_T3_1_CB);

  TGLShowMesh_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                       392,
                                       534,
                                       1883,
                                       119,
                               "Show Mesh",
                               TGLShowMesh_TOG_T3_1_CB);

  BTNSelGB_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                    5297,
                                    2429,
                                    1219,
                                    142,
                    "Select GB",
                    BTNSelGB_BTN_T3_1_CB);

  TFGrpNum_TF_T3_1 = TecGUITextFieldAdd(Tab3_1Manager,
                                      4471,
                                      2429,
                                      718,
                                      142,
                       TFGrpNum_TF_T3_1_CB);

  LBL20_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                3698,
                                2469,
                    "Group #");

  LBL21_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                3698,
                                2128,
                    "1. Activate boundary w/ toggle mode\n2. Select GB within boundary");

  BTNFndBas_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                     7302,
                                     312,
                                     1991,
                                     233,
                    "Find Special \nGradient Bundles",
                    BTNFndBas_BTN_T3_1_CB);

  BTNSmooth_BTN_T3_1 = TecGUIButtonAdd(Tab3_1Manager,
                                     2330,
                                     2492,
                                     1002,
                                     142,
                    "Smooth",
                    BTNSmooth_BTN_T3_1_CB);

  TGLSmoothAll_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                        501,
                                        2509,
                                        1842,
                                        119,
                               "All spheres",
                               TGLSmoothAll_TOG_T3_1_CB);

  SCRad_SC_T3_1 = TecGUIScaleAdd(Tab3_1Manager,
                               447,
                               1257,
                               2601,
                               108,
                    0,
                    100,
                    0,
                    SCRad_SC_T3_1_CB,
                    SCRad_SCD_T3_1_CB);


  TecGUIScaleShowNumericDisplay(SCRad_SC_T3_1,FALSE);

  TGLRadAll_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                     487,
                                     1086,
                                     1869,
                                     119,
                               "All Spheres",
                               TGLRadAll_TOG_T3_1_CB);

  TGLRadAbs_TOG_T3_1 = TecGUIToggleAdd(Tab3_1Manager,
                                     1883,
                                     1086,
                                     1598,
                                     119,
                               "Absolute",
                               TGLRadAbs_TOG_T3_1_CB);

  LBL27_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                487,
                                916,
                    "Radius:");

  LBLRadLab_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                    3102,
                                    1246,
                    "Label");

  LBL29_LBL_T3_1 = TecGUILabelAdd(Tab3_1Manager,
                                7329,
                                2298,
                    "Uncheck to only include active.");

}

/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             10550,
                                             3262,
                                             "Gradient Bundle Analysis",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             NULL)
;  TAB1_TB_D1 = TecGUITabAdd(Dialog1Manager,
                          40,
                          187,
                          10459,
                          3050,
                    TAB1_TBA_D1_CB,
                    TAB1_TBD_D1_CB);

  BuildTab1_1(TAB1_TB_D1);
  BuildTab3_1(TAB1_TB_D1);
}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
