/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Tab1_1Manager = BADDIALOGID;
LgIndex_t BTNRun_BTN_T1_1 = BADDIALOGID;
LgIndex_t TFSTPts_TF_T1_1 = BADDIALOGID;
LgIndex_t LBLSTPts_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLNumTri_LBL_T1_1 = BADDIALOGID;
LgIndex_t TFRad_TF_T1_1 = BADDIALOGID;
LgIndex_t LBLRad_LBL_T1_1 = BADDIALOGID;
LgIndex_t RBRadMode_RADIO_T1_1 = BADDIALOGID;
LgIndex_t TFCutoff_TF_T1_1 = BADDIALOGID;
LgIndex_t LBLCutoff_LBL_T1_1 = BADDIALOGID;
LgIndex_t MLSelVars_MLST_T1_1 = BADDIALOGID;
LgIndex_t SCPrecise_SC_T1_1 = BADDIALOGID;
LgIndex_t LBLPreci1_LBL_T1_1 = BADDIALOGID;
LgIndex_t MLSelCPs_MLST_T1_1 = BADDIALOGID;
LgIndex_t LBLPrecise_LBL_T1_1 = BADDIALOGID;
LgIndex_t TGLsGP_TOG_T1_1 = BADDIALOGID;
LgIndex_t TGLsGB_TOG_T1_1 = BADDIALOGID;
LgIndex_t LBLLevel_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLBPGBa_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLGBMaxSD_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLSDtightle_LBL_T1_1 = BADDIALOGID;
LgIndex_t TGLNoSphInt_TOG_T1_1 = BADDIALOGID;
LgIndex_t SCSDtight_SC_T1_1 = BADDIALOGID;
LgIndex_t SCBPGBs_SC_T1_1 = BADDIALOGID;
LgIndex_t SCEGPDist_SC_T1_1 = BADDIALOGID;
LgIndex_t LBLSDtight_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLBPGBs_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLEGPDistTy_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLBPGBi_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLBPGBInit_LBL_T1_1 = BADDIALOGID;
LgIndex_t SCMinGBs_SC_T1_1 = BADDIALOGID;
LgIndex_t SCBPGBInit_SC_T1_1 = BADDIALOGID;
LgIndex_t TGLSphTest_TOG_T1_1 = BADDIALOGID;
LgIndex_t TGL_TOG_T1_1 = BADDIALOGID;
LgIndex_t Tab3_1Manager = BADDIALOGID;
LgIndex_t SLSelSphere_SLST_T3_1 = BADDIALOGID;
LgIndex_t TGLSphereVis_TOG_T3_1 = BADDIALOGID;
LgIndex_t BTNSphereDel_BTN_T3_1 = BADDIALOGID;
LgIndex_t SLSelVar_SLST_T3_1 = BADDIALOGID;
LgIndex_t MLSelGB_MLST_T3_1 = BADDIALOGID;
LgIndex_t BTNAllGB_BTN_T3_1 = BADDIALOGID;
LgIndex_t BTNTogMode_BTN_T3_1 = BADDIALOGID;
LgIndex_t TFNumContours_TF_T3_1 = BADDIALOGID;
LgIndex_t LBL9_LBL_T3_1 = BADDIALOGID;
LgIndex_t RBLogLin_RADIO_T3_1 = BADDIALOGID;
LgIndex_t RBCntSrc_RADIO_T3_1 = BADDIALOGID;
LgIndex_t LBLCntSrc_LBL_T3_1 = BADDIALOGID;
LgIndex_t LBL13_LBL_T3_1 = BADDIALOGID;
LgIndex_t BTNExport_BTN_T3_1 = BADDIALOGID;
LgIndex_t TGLExGBs_TOG_T3_1 = BADDIALOGID;
LgIndex_t TGLShowMesh_TOG_T3_1 = BADDIALOGID;
LgIndex_t BTNSelGB_BTN_T3_1 = BADDIALOGID;
LgIndex_t TFGrpNum_TF_T3_1 = BADDIALOGID;
LgIndex_t LBL20_LBL_T3_1 = BADDIALOGID;
LgIndex_t LBL21_LBL_T3_1 = BADDIALOGID;
LgIndex_t BTNFndBas_BTN_T3_1 = BADDIALOGID;
LgIndex_t BTNSmooth_BTN_T3_1 = BADDIALOGID;
LgIndex_t TGLSmoothAll_TOG_T3_1 = BADDIALOGID;
LgIndex_t SCRad_SC_T3_1 = BADDIALOGID;
LgIndex_t TGLRadAll_TOG_T3_1 = BADDIALOGID;
LgIndex_t TGLRadAbs_TOG_T3_1 = BADDIALOGID;
LgIndex_t LBL27_LBL_T3_1 = BADDIALOGID;
LgIndex_t LBLRadLab_LBL_T3_1 = BADDIALOGID;
LgIndex_t LBL29_LBL_T3_1 = BADDIALOGID;
LgIndex_t TGL_TOG_T3_1 = BADDIALOGID;
LgIndex_t LBL31_LBL_T3_1 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t TAB1_TB_D1 = BADDIALOGID;
