/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Tab1_1Manager = BADDIALOGID;
LgIndex_t BTNRun_BTN_T1_1 = BADDIALOGID;
LgIndex_t TFSTPts_TF_T1_1 = BADDIALOGID;
LgIndex_t LBL19_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLGPperGB_LBL_T1_1 = BADDIALOGID;
LgIndex_t SCNumEdgeGPs_SC_T1_1 = BADDIALOGID;
LgIndex_t LBL20_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLNumTri_LBL_T1_1 = BADDIALOGID;
LgIndex_t TFLevel_TFS_T1_1 = BADDIALOGID;
LgIndex_t TFRad_TF_T1_1 = BADDIALOGID;
LgIndex_t LBLRad_LBL_T1_1 = BADDIALOGID;
LgIndex_t RBRadMode_RADIO_T1_1 = BADDIALOGID;
LgIndex_t TFCutoff_TF_T1_1 = BADDIALOGID;
LgIndex_t LBLCutoff_LBL_T1_1 = BADDIALOGID;
LgIndex_t TGLOpenSys_TOG_T1_1 = BADDIALOGID;
LgIndex_t MLSelVars_MLST_T1_1 = BADDIALOGID;
LgIndex_t SCPrecise_SC_T1_1 = BADDIALOGID;
LgIndex_t LBL23_LBL_T1_1 = BADDIALOGID;
LgIndex_t TGLVolInt_TOG_T1_1 = BADDIALOGID;
LgIndex_t TGLInt_TOG_T1_1 = BADDIALOGID;
LgIndex_t MLSelCPs_MLST_T1_1 = BADDIALOGID;
LgIndex_t LBLLevel_LBL_T1_1 = BADDIALOGID;
LgIndex_t LBLPrecise_LBL_T1_1 = BADDIALOGID;
LgIndex_t Tab2_1Manager = BADDIALOGID;
LgIndex_t MLIntSelSph_MLST_T2_1 = BADDIALOGID;
LgIndex_t MLIntSelVar_MLST_T2_1 = BADDIALOGID;
LgIndex_t TGLIntVolInt_TOG_T2_1 = BADDIALOGID;
LgIndex_t LBL6_LBL_T2_1 = BADDIALOGID;
LgIndex_t SCIntPrecise_SC_T2_1 = BADDIALOGID;
LgIndex_t BTNIntegrate_BTN_T2_1 = BADDIALOGID;
LgIndex_t LBLIntPrecis_LBL_T2_1 = BADDIALOGID;
LgIndex_t Tab3_1Manager = BADDIALOGID;
LgIndex_t SLSelSphere_SLST_T3_1 = BADDIALOGID;
LgIndex_t TGLSphereVis_TOG_T3_1 = BADDIALOGID;
LgIndex_t BTNSphereDel_BTN_T3_1 = BADDIALOGID;
LgIndex_t SLSelVar_SLST_T3_1 = BADDIALOGID;
LgIndex_t MLSelGB_MLST_T3_1 = BADDIALOGID;
LgIndex_t BTNAllGB_BTN_T3_1 = BADDIALOGID;
LgIndex_t BTNTogMode_BTN_T3_1 = BADDIALOGID;
LgIndex_t TFNumContours_TF_T3_1 = BADDIALOGID;
LgIndex_t LBL9_LBL_T3_1 = BADDIALOGID;
LgIndex_t RBLogLin_RADIO_T3_1 = BADDIALOGID;
LgIndex_t RBCntSrc_RADIO_T3_1 = BADDIALOGID;
LgIndex_t LBLCntSrc_LBL_T3_1 = BADDIALOGID;
LgIndex_t LBL13_LBL_T3_1 = BADDIALOGID;
LgIndex_t BTNExport_BTN_T3_1 = BADDIALOGID;
LgIndex_t TGLExGBs_TOG_T3_1 = BADDIALOGID;
LgIndex_t TGLExInt_TOG_T3_1 = BADDIALOGID;
LgIndex_t TGLShowMesh_TOG_T3_1 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t TAB1_TB_D1 = BADDIALOGID;
