/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Sidebar1Manager = BADDIALOGID;
LgIndex_t LabGTATitle_LBL_S1 = BADDIALOGID;
LgIndex_t LabCPList_LBL_S1 = BADDIALOGID;
LgIndex_t MLCPs_MLST_S1 = BADDIALOGID;
LgIndex_t PBSelectCPs_BTN_S1 = BADDIALOGID;
LgIndex_t PBClear_BTN_S1 = BADDIALOGID;
LgIndex_t LabCutoffVar_LBL_S1 = BADDIALOGID;
LgIndex_t LabAngleStep_LBL_S1 = BADDIALOGID;
LgIndex_t LBL14_LBL_S1 = BADDIALOGID;
LgIndex_t LBL15_LBL_S1 = BADDIALOGID;
LgIndex_t OptSliceAngl_OPT_S1 = BADDIALOGID;
LgIndex_t OptStreamAng_OPT_S1 = BADDIALOGID;
LgIndex_t TGLDeleteZon_TOG_S1 = BADDIALOGID;
LgIndex_t PBQuit_BTN_S1 = BADDIALOGID;
LgIndex_t PBRun_BTN_S1 = BADDIALOGID;
LgIndex_t TGLHideZones_TOG_S1 = BADDIALOGID;
LgIndex_t MLSelectVar_MLST_S1 = BADDIALOGID;
LgIndex_t LabSelectVar_LBL_S1 = BADDIALOGID;
LgIndex_t LabCutoffVal_LBL_S1 = BADDIALOGID;
LgIndex_t TFCutoff_TF_S1 = BADDIALOGID;
LgIndex_t RBCutoffDi_RADIO_S1 = BADDIALOGID;
LgIndex_t OPTCutoffVar_OPT_S1 = BADDIALOGID;
LgIndex_t LabRadOff_LBL_S1 = BADDIALOGID;
LgIndex_t TFRadOffVal_TF_S1 = BADDIALOGID;
LgIndex_t TGLShowOnly_TOG_S1 = BADDIALOGID;
LgIndex_t TFStBegAng_TF_S1 = BADDIALOGID;
LgIndex_t TFSlcBegAng_TF_S1 = BADDIALOGID;
LgIndex_t TFSlcEndAng_TF_S1 = BADDIALOGID;
LgIndex_t TFStEndAng_TF_S1 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t LabCTRLRem_LBL_D1 = BADDIALOGID;
