/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Sidebar1Manager;
extern void BuildSidebar1(void);
extern LgIndex_t  LabGTATitle_LBL_S1;
extern LgIndex_t  LabCPList_LBL_S1;
extern LgIndex_t  MLCPs_MLST_S1;
extern LgIndex_t  PBSelectCPs_BTN_S1;
extern LgIndex_t  PBClear_BTN_S1;
extern LgIndex_t  LabCutoffVar_LBL_S1;
extern LgIndex_t  LabAngleStep_LBL_S1;
extern LgIndex_t  LBL14_LBL_S1;
extern LgIndex_t  LBL15_LBL_S1;
extern LgIndex_t  OptSliceAngl_OPT_S1;
extern LgIndex_t  OptStreamAng_OPT_S1;
extern LgIndex_t  TGLDeleteZon_TOG_S1;
extern LgIndex_t  PBQuit_BTN_S1;
extern LgIndex_t  PBRun_BTN_S1;
extern LgIndex_t  TGLHideZones_TOG_S1;
extern LgIndex_t  MLSelectVar_MLST_S1;
extern LgIndex_t  LabSelectVar_LBL_S1;
extern LgIndex_t  LabCutoffVal_LBL_S1;
extern LgIndex_t  TFCutoff_TF_S1;
extern LgIndex_t  RBCutoffDi_RADIO_S1;
extern LgIndex_t  OPTCutoffVar_OPT_S1;
extern LgIndex_t  LabRadOff_LBL_S1;
extern LgIndex_t  TFRadOffVal_TF_S1;
extern LgIndex_t  TGLShowOnly_TOG_S1;
extern LgIndex_t  TFStBegAng_TF_S1;
extern LgIndex_t  TFSlcBegAng_TF_S1;
extern LgIndex_t  TFSlcEndAng_TF_S1;
extern LgIndex_t  TFStEndAng_TF_S1;
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  LabCTRLRem_LBL_D1;
