/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4358,
                                          3132,
                                          "Scalar Gradient Topology",
                                          Dialog1Init_CB,
                                          Dialog1OkButton_CB,
                                          NULL,
                                          Dialog1CancelButton_CB,
                                          Dialog1HelpButton_CB);
  LBL1_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             217,
                             141,
                    "Source Zone:");

  SourceZone_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                        1862,
                                        100,
                                        1982,
                                        141,
                        SourceZone_OPT_D1_List,
                        SourceZone_OPT_D1_CB);

  LBL13_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              217,
                              324,
                    "Refined Grids:");

  RefinedGrid_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                    1862,
                                    292,
                                    2069,
                                    1052,
                       1,
                       RefinedGrid_MLST_D1_CB);

  LBL3_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             217,
                             1605,
                    "Scalar Var:");

  ScalarVarNum_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                          1862,
                                          1564,
                                          1982,
                                          141,
                        ScalarVarNum_OPT_D1_List,
                        ScalarVarNum_OPT_D1_CB);

  LBL5_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             217,
                             1788,
                    "Grad_x:");

  GradXVar_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                      1862,
                                      1747,
                                      1982,
                                      141,
                        GradXVar_OPT_D1_List,
                        GradXVar_OPT_D1_CB);

  LBL7_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             217,
                             1971,
                    "Grad_y:");

  GradYVar_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                      1862,
                                      1930,
                                      1982,
                                      141,
                        GradYVar_OPT_D1_List,
                        GradYVar_OPT_D1_CB);

  LBL9_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             217,
                             2154,
                    "Grad_z:");

  GradZVar_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                      1862,
                                      2113,
                                      1982,
                                      141,
                        GradZVar_OPT_D1_List,
                        GradZVar_OPT_D1_CB);

  PeriodicBC_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                    217,
                                    2854,
                                    3692,
                                    128,
                               "Periodic Boundary Conditions",
                               PeriodicBC_TOG_D1_CB);

  LBL14_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              217,
                              2337,
                    "Grad_Tot:");

  GradTot_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                     1862,
                                     2296,
                                     1982,
                                     141,
                        GradTot_OPT_D1_List,
                        GradTot_OPT_D1_CB);

  LBL16_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              217,
                              2703,
                    "Compute:");

  ComputeOptio_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                          1862,
                                          2662,
                                          1982,
                                          141,
                        ComputeOptio_OPT_D1_List,
                        ComputeOptio_OPT_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
