/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  LBL1_LBL_D1;
extern LgIndex_t  SourceZone_OPT_D1;
extern LgIndex_t  LBL13_LBL_D1;
extern LgIndex_t  RefinedGrid_MLST_D1;
extern LgIndex_t  LBL3_LBL_D1;
extern LgIndex_t  ScalarVarNum_OPT_D1;
extern LgIndex_t  LBL5_LBL_D1;
extern LgIndex_t  GradXVar_OPT_D1;
extern LgIndex_t  LBL7_LBL_D1;
extern LgIndex_t  GradYVar_OPT_D1;
extern LgIndex_t  LBL9_LBL_D1;
extern LgIndex_t  GradZVar_OPT_D1;
extern LgIndex_t  PeriodicBC_TOG_D1;
extern LgIndex_t  LBL14_LBL_D1;
extern LgIndex_t  GradTot_OPT_D1;
extern LgIndex_t  LBL16_LBL_D1;
extern LgIndex_t  ComputeOptio_OPT_D1;
