/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildSidebar1(void)
{
  if (Sidebar1Manager != BADDIALOGID)
    return;

  Sidebar1Manager = TecGUISidebarRegister("Bondalyzer",
                                      AddOnID,
                                      2240,
                                      3385,
                                      Sidebar1Activate_CB,
                                      Sidebar1Deactivate_CB);
  WhatToShow_LBL_S1 = TecGUILabelAdd(Sidebar1Manager,
                                   114,
                                   92,
                    "Show");

  AtomOrBond_LBL_S1 = TecGUILabelAdd(Sidebar1Manager,
                                   114,
                                   398,
                    "Atoms/Bonds");

  AtomOrBond_MLST_S1 = TecGUIListAdd(Sidebar1Manager,
                                   19,
                                   510,
                                   2202,
                                   599,
                       1,
                       AtomOrBond_MLST_S1_CB);

  Info_LBL_S1 = TecGUILabelAdd(Sidebar1Manager,
                             114,
                             1166,
                    "Info");

  Info_T_S1 = TecGUITextAdd(Sidebar1Manager,
                          19,
                          1279,
                          2183,
                          1689,
                       1,
                       NULL);

  ReturnToTecp_BTN_S1 = TecGUIButtonAdd(Sidebar1Manager,
                                      19,
                                      3113,
                                      1982,
                                      144,
                    "Return to Tecplot",
                    ReturnToTecp_BTN_S1_CB);

  WhatToShow_OPT_S1 = TecGUIOptionMenuAdd(Sidebar1Manager,
                                        19,
                                        205,
                                        2173,
                                        144,
                        WhatToShow_OPT_S1_List,
                        WhatToShow_OPT_S1_CB);

}

/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             5482,
                                             2781,
                                             "Chemistry Bond Topology",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  LBL1_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             335,
                             197,
                    "Zone:");

  SourceZone_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                        1034,
                                        148,
                                        1350,
                                        144,
                        SourceZone_OPT_D1_List,
                        SourceZone_OPT_D1_CB);

  ComputeTopo_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                     3026,
                                     132,
                                     1982,
                                     144,
                    "Extract Topology",
                    ComputeTopo_BTN_D1_CB);

  CPType_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                    2489,
                                    386,
                                    1350,
                                    144,
                        CPType_OPT_D1_List,
                        CPType_OPT_D1_CB);

  LBL5_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             277,
                             422,
                    "Critical Point Type:");

  BondList_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                 287,
                                 756,
                                 1378,
                                 599,
                       1,
                       BondList_MLST_D1_CB);

  AtomList_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                 2250,
                                 740,
                                 1378,
                                 599,
                       1,
                       AtomList_MLST_D1_CB);

  RingList_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                 373,
                                 1540,
                                 1378,
                                 599,
                       1,
                       RingList_MLST_D1_CB);

  CageList_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                 2288,
                                 1548,
                                 1378,
                                 599,
                       1,
                       CageList_MLST_D1_CB);

  LBL10_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              296,
                              635,
                    "Bonds:");

  LBL11_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              2221,
                              615,
                    "Atoms:");

  LBL12_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              430,
                              1435,
                    "Rings:");

  LBL13_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              2279,
                              1439,
                    "Cages:");

  LBL14_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              363,
                              2264,
                    "Depiction:");

  ImageType_OPT_D1 = TecGUIOptionMenuAdd(Dialog1Manager,
                                       1465,
                                       2232,
                                       1350,
                                       144,
                        ImageType_OPT_D1_List,
                        ImageType_OPT_D1_CB);

  ShowNeighbor_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                      363,
                                      2489,
                                      3332,
                                      116,
                               "Show Neighboring Atoms",
                               ShowNeighbor_TOG_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
