/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Sidebar1Manager = BADDIALOGID;
LgIndex_t WhatToShow_LBL_S1 = BADDIALOGID;
LgIndex_t AtomOrBond_LBL_S1 = BADDIALOGID;
LgIndex_t AtomOrBond_MLST_S1 = BADDIALOGID;
LgIndex_t Info_LBL_S1 = BADDIALOGID;
LgIndex_t Info_T_S1 = BADDIALOGID;
LgIndex_t ReturnToTecp_BTN_S1 = BADDIALOGID;
LgIndex_t WhatToShow_OPT_S1 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t LBL1_LBL_D1 = BADDIALOGID;
LgIndex_t SourceZone_OPT_D1 = BADDIALOGID;
LgIndex_t ComputeTopo_BTN_D1 = BADDIALOGID;
LgIndex_t CPType_OPT_D1 = BADDIALOGID;
LgIndex_t LBL5_LBL_D1 = BADDIALOGID;
LgIndex_t BondList_MLST_D1 = BADDIALOGID;
LgIndex_t AtomList_MLST_D1 = BADDIALOGID;
LgIndex_t RingList_MLST_D1 = BADDIALOGID;
LgIndex_t CageList_MLST_D1 = BADDIALOGID;
LgIndex_t LBL10_LBL_D1 = BADDIALOGID;
LgIndex_t LBL11_LBL_D1 = BADDIALOGID;
LgIndex_t LBL12_LBL_D1 = BADDIALOGID;
LgIndex_t LBL13_LBL_D1 = BADDIALOGID;
LgIndex_t LBL14_LBL_D1 = BADDIALOGID;
LgIndex_t ImageType_OPT_D1 = BADDIALOGID;
LgIndex_t ShowNeighbor_TOG_D1 = BADDIALOGID;
