/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
    if (Dialog1Manager != BADDIALOGID)
        return;

    Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                             4383,
                                             764,
                                             "Load Values",
                                             Dialog1Init_CB,
                                             Dialog1OkButton_CB,
                                             NULL,
                                             Dialog1CancelButton_CB,
                                             Dialog1HelpButton_CB);
    FileName_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                        852,
                                        530,
                                        2710,
                                        144,
                                        FileName_TF_D1_CB);

    Browse_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                    3733,
                                    530,
                                    375,
                                    144,
                                    "...",
                                    Browse_BTN_D1_CB);

    CreateFile_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                        409,
                                        128,
                                        1670,
                                        144,
                                        "Make Test File",
                                        CreateFile_BTN_D1_CB);

    LBL1_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                 306,
                                 583,
                                 "File:");

}

/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
    if (Dialog2Manager != BADDIALOGID)
        return;

    Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                             5559,
                                             862,
                                             "MakeValueFile",
                                             Dialog2Init_CB,
                                             Dialog2OkButton_CB,
                                             NULL,
                                             Dialog2CancelButton_CB,
                                             Dialog2HelpButton_CB);
    LBL1_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                 136,
                                 151,
                                 "IMax ");

    LBL3_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                 136,
                                 500,
                                 "JMax");

    LBL7_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                 1858,
                                 500,
                                 "Y Start");

    LBL8_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                 3682,
                                 500,
                                 "Y Delta");

    LBL5_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                 1858,
                                 151,
                                 "X Start");

    LBL6_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                                 3682,
                                 151,
                                 "X Delta");

    IMax_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                    682,
                                    128,
                                    869,
                                    144,
                                    IMax_TF_D2_CB);

    YStart_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                      2557,
                                      492,
                                      869,
                                      144,
                                      YStart_TF_D2_CB);

    XDelta_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                      4415,
                                      128,
                                      869,
                                      144,
                                      XDelta_TF_D2_CB);

    YDelta_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                      4415,
                                      492,
                                      869,
                                      144,
                                      YDelta_TF_D2_CB);

    XStart_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                      2557,
                                      128,
                                      869,
                                      144,
                                      XStart_TF_D2_CB);

    JMax_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                    682,
                                    492,
                                    869,
                                    144,
                                    JMax_TF_D2_CB);

}


/**
 */
void InitTGB(void)
{
    /* Currently not used */
}
