/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  FileName_TF_D1;
extern LgIndex_t  Browse_BTN_D1;
extern LgIndex_t  CreateFile_BTN_D1;
extern LgIndex_t  LBL1_LBL_D1;
extern LgIndex_t Dialog2Manager;
extern void BuildDialog2(LgIndex_t  ParentDialog);

extern LgIndex_t  LBL1_LBL_D2;
extern LgIndex_t  LBL3_LBL_D2;
extern LgIndex_t  LBL7_LBL_D2;
extern LgIndex_t  LBL8_LBL_D2;
extern LgIndex_t  LBL5_LBL_D2;
extern LgIndex_t  LBL6_LBL_D2;
extern LgIndex_t  IMax_TF_D2;
extern LgIndex_t  YStart_TF_D2;
extern LgIndex_t  XDelta_TF_D2;
extern LgIndex_t  YDelta_TF_D2;
extern LgIndex_t  XStart_TF_D2;
extern LgIndex_t  JMax_TF_D2;
