/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t FileName_TF_D1 = BADDIALOGID;
LgIndex_t Browse_BTN_D1 = BADDIALOGID;
LgIndex_t CreateFile_BTN_D1 = BADDIALOGID;
LgIndex_t LBL1_LBL_D1 = BADDIALOGID;
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t LBL1_LBL_D2 = BADDIALOGID;
LgIndex_t LBL3_LBL_D2 = BADDIALOGID;
LgIndex_t LBL7_LBL_D2 = BADDIALOGID;
LgIndex_t LBL8_LBL_D2 = BADDIALOGID;
LgIndex_t LBL5_LBL_D2 = BADDIALOGID;
LgIndex_t LBL6_LBL_D2 = BADDIALOGID;
LgIndex_t IMax_TF_D2 = BADDIALOGID;
LgIndex_t YStart_TF_D2 = BADDIALOGID;
LgIndex_t XDelta_TF_D2 = BADDIALOGID;
LgIndex_t YDelta_TF_D2 = BADDIALOGID;
LgIndex_t XStart_TF_D2 = BADDIALOGID;
LgIndex_t JMax_TF_D2 = BADDIALOGID;
