/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t BTN1_BTN_D1 = BADDIALOGID;
