/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t OPT2_OPT_D2 = BADDIALOGID;
LgIndex_t OPT3_OPT_D2 = BADDIALOGID;
LgIndex_t OPT4_OPT_D2 = BADDIALOGID;
LgIndex_t OPT5_OPT_D2 = BADDIALOGID;
LgIndex_t LBL1_LBL_D2 = BADDIALOGID;
LgIndex_t Dialog3Manager = BADDIALOGID;
LgIndex_t OPT2_OPT_D3 = BADDIALOGID;
LgIndex_t OPT1_OPT_D3 = BADDIALOGID;
LgIndex_t Dialog4Manager = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t BTN1_BTN_D1 = BADDIALOGID;
LgIndex_t LBLVolZone_LBL_D1 = BADDIALOGID;
LgIndex_t OPT4_OPT_D1 = BADDIALOGID;
LgIndex_t TGLPerSys_TOG_D1 = BADDIALOGID;
LgIndex_t LBLRhoVar_LBL_D1 = BADDIALOGID;
LgIndex_t OPTRhoVar_OPT_D1 = BADDIALOGID;
LgIndex_t LBLX_LBL_D1 = BADDIALOGID;
LgIndex_t LBLY_LBL_D1 = BADDIALOGID;
LgIndex_t LBLZ_LBL_D1 = BADDIALOGID;
LgIndex_t OPTZ_OPT_D1 = BADDIALOGID;
LgIndex_t OPTX_OPT_D1 = BADDIALOGID;
LgIndex_t OPTY_OPT_D1 = BADDIALOGID;
