/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildTab1_1(LgIndex_t  Parent)
{
  if (Tab1_1Manager != BADDIALOGID)
    return;

  Tab1_1Manager = TecGUITabAddPage(Parent,
                               "Export script and import Tape41");
  ExportBTN_BTN_T1_1 = TecGUIButtonAdd(Tab1_1Manager,
                                     38,
                                     2966,
                                     2166,
                                     142,
                    "Export densf script",
                    ExportBTN_BTN_T1_1_CB);

  ImportBTN_BTN_T1_1 = TecGUIButtonAdd(Tab1_1Manager,
                                     2787,
                                     2966,
                                     2166,
                                     142,
                    "Import Tape41 files",
                    ImportBTN_BTN_T1_1_CB);

  ZoneList_MLST_T1_1 = TecGUIListAdd(Tab1_1Manager,
                                   38,
                                   53,
                                   4915,
                                   2872,
                       1,
                       ZoneList_MLST_T1_1_CB);

}

/**
 */
void BuildTab2_1(LgIndex_t  Parent)
{
  if (Tab2_1Manager != BADDIALOGID)
    return;

  Tab2_1Manager = TecGUITabAddPage(Parent,
                               "Instructions");
  InfoText_LBL_T2_1 = TecGUILabelAdd(Tab2_1Manager,
                                   145,
                                   61,
                    "Label                                                                          I\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nL                                                                                 I");

}

/**
 */
void BuildDialog3(LgIndex_t  ParentDialog)
{
  if (Dialog3Manager != BADDIALOGID)
    return;

  Dialog3Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             5228,
                                             3400,
                                             "Refine zone data",
                                             Dialog3Init_CB,
                                             Dialog3CloseButton_CB,
                                             nullptr)
;  TAB1_TB_D3 = TecGUITabAdd(Dialog3Manager,
                          29,
                          220,
                          5177,
                          3145,
                    TAB1_TBA_D3_CB,
                    TAB1_TBD_D3_CB);

  BuildTab1_1(TAB1_TB_D3);
  BuildTab2_1(TAB1_TB_D3);
}

/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4383,
                                          2144,
                                          "Untitled",
                                          Dialog1Init_CB,
                                          Dialog1OkButton_CB,
                                          nullptr,
                                          Dialog1CancelButton_CB,
                                          Dialog1HelpButton_CB);
  MLT41LoadVa_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                    145,
                                    195,
                                    4089,
                                    1689,
                       1,
                       MLT41LoadVa_MLST_D1_CB);

  LabLoaderSel_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                     194,
                                     61,
                    "Select variables to load:");

}

/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                          3888,
                                          780,
                                          "Untitled",
                                          Dialog2Init_CB,
                                          Dialog2OkButton_CB,
                                          nullptr,
                                          Dialog2CancelButton_CB,
                                          Dialog2HelpButton_CB);
  LBL2_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             466,
                             301,
                    "X");

  LBL3_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             1641,
                             301,
                    "Y");

  LBL4_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             2817,
                             301,
                    "Z");

  XNC_TFS_D2 = TecGUISpinTextFieldAdd(Dialog2Manager,
                                    165,
                                    412,
                                    796,
                                    142,
                       XNC_TFS_D2_ValueChanged_CB,
                       XNC_TFS_D2_ButtonUp_CB,
                       XNC_TFS_D2_ButtonDown_CB);

  YNC_TFS_D2 = TecGUISpinTextFieldAdd(Dialog2Manager,
                                    1340,
                                    412,
                                    796,
                                    142,
                       YNC_TFS_D2_ValueChanged_CB,
                       YNC_TFS_D2_ButtonUp_CB,
                       YNC_TFS_D2_ButtonDown_CB);

  ZNC_TFS_D2 = TecGUISpinTextFieldAdd(Dialog2Manager,
                                    2515,
                                    412,
                                    796,
                                    142,
                       ZNC_TFS_D2_ValueChanged_CB,
                       ZNC_TFS_D2_ButtonUp_CB,
                       ZNC_TFS_D2_ButtonDown_CB);

  LBL8_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             553,
                             632,
                    "* 1 x 1 x 1 is simulation size *");

  LBL1_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             369,
                             24,
                    "Select number of cells to expand \nsystem in  X, Y, Z directions:");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
