/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#if defined MSWIN
#include "STDAFX.h"
#endif
#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Tab1_1Manager = BADDIALOGID;
LgIndex_t ExportBTN_BTN_T1_1 = BADDIALOGID;
LgIndex_t ImportBTN_BTN_T1_1 = BADDIALOGID;
LgIndex_t ZoneList_MLST_T1_1 = BADDIALOGID;
LgIndex_t Tab2_1Manager = BADDIALOGID;
LgIndex_t InfoText_LBL_T2_1 = BADDIALOGID;
LgIndex_t Dialog3Manager = BADDIALOGID;
LgIndex_t TAB1_TB_D3 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t MLT41LoadVa_MLST_D1 = BADDIALOGID;
LgIndex_t LabLoaderSel_LBL_D1 = BADDIALOGID;
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t LBL2_LBL_D2 = BADDIALOGID;
LgIndex_t LBL3_LBL_D2 = BADDIALOGID;
LgIndex_t LBL4_LBL_D2 = BADDIALOGID;
LgIndex_t XNC_TFS_D2 = BADDIALOGID;
LgIndex_t YNC_TFS_D2 = BADDIALOGID;
LgIndex_t ZNC_TFS_D2 = BADDIALOGID;
LgIndex_t LBL8_LBL_D2 = BADDIALOGID;
LgIndex_t LBL1_LBL_D2 = BADDIALOGID;
