/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Tab1_1Manager;
extern void BuildTab1_1(LgIndex_t  Parent);

extern LgIndex_t  ExportBTN_BTN_T1_1;
extern LgIndex_t  ImportBTN_BTN_T1_1;
extern LgIndex_t  ZoneList_MLST_T1_1;
extern LgIndex_t Tab2_1Manager;
extern void BuildTab2_1(LgIndex_t  Parent);

extern LgIndex_t  InfoText_LBL_T2_1;
extern LgIndex_t Dialog3Manager;
extern void BuildDialog3(LgIndex_t  ParentDialog);

extern LgIndex_t  TAB1_TB_D3;
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  MLT41LoadVa_MLST_D1;
extern LgIndex_t  LabLoaderSel_LBL_D1;
extern LgIndex_t Dialog2Manager;
extern void BuildDialog2(LgIndex_t  ParentDialog);

extern LgIndex_t  LBL2_LBL_D2;
extern LgIndex_t  LBL3_LBL_D2;
extern LgIndex_t  LBL4_LBL_D2;
extern LgIndex_t  XNC_TFS_D2;
extern LgIndex_t  YNC_TFS_D2;
extern LgIndex_t  ZNC_TFS_D2;
extern LgIndex_t  LBL8_LBL_D2;
extern LgIndex_t  LBL1_LBL_D2;
